version: 1.0.0
server:
  port: 12021

spring:
  application:
    version: 1.0.1
    description: @dev环境
axinger:
  config:
    username: jim
    password: 1234
  person:
    id: 1
  doc:
    title: mvc测试

show:
  # 湿度
  humidity:
    min: 40.0
    max: 65.0
  # 温度
  temperature:
    min: 150
    max: 300



