server:
  servlet:
    context-path: /
    encoding:
      force: true
      charset: utf-8
      enabled: true
  port: 8073

spring:
  application:
    name: demo-seata-storage
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/demo_seata_storage?characterEncoding=utf-8&useSSL=false

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: my-test-tx-group

feign:
  hystrix:
    enabled: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.ax.seata.mapper



#seata:
#  enabled: true
#  application-id: ${spring.application.name} #微服务应用名称
#  tx-service-group: my-test-tx-group    #此处配置自定义的seata事务分组名称
#  enable-auto-data-source-proxy: true    #开启数据库代理
#  registry:
#    type: nacos
#    nacos:
#      application: ${spring.application.name}
#      server-addr: localhost:8848 #注册中心nacos地址
#      group: SEATA_GROUP #分组名 对应服务器端配置
#      cluster: default #默认集群名
#  config:
#    type: nacos
#    nacos:
#      server-addr: localhost:8848 #配置中心nacos地址
#      group: SEATA_GROUP #分组名 对应服务器端配置
#      namespace: public  #命名空间 对应nacos中配置中心seata
#  service:
#    vgroup-mapping:
#      my-test-tx-group: default
seata:
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: "SEATA_GROUP"
      namespace: ""
      dataId: "seataServer.properties"
      username: "nacos"
      password: "nacos"
