server:
  port: 12010

rocketmq:
  #  name-server: hadoop102:9876 # 访问地址

  producer:

    group: test # 必须指定group
    send-message-timeout: 30000 # 消息发送超时时长，默认3s
  #    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
  #    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
  consumer:
    group: sys_msg_group
#    pull-batch-size: 3

